branch-defaults:
  main:
    environment: Hummingbird-env-1
environment-defaults:
  Hummingbird-env:
    branch: null
    repository: null
  Hummingbird-env-1:
    branch: null
    repository: null
global:
  application_name: Hummingbird
  default_ec2_keyname: null
  default_platform: Ruby 2.7 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
